const PRIMARY_COLOR = "#E60000"
const SECONDARY_COLOR = "#282D30"
const TOOLTIP_COLOR = "#C4C4C4"
const RADIANT_COLOR = "#FFFFFF"
const WHITE_COLOR = "#FFFFFF"
const TEXT_COLOR = "#000000"

export default {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  TOOLTIP_COLOR,
  RADIANT_COLOR,
  WHITE_COLOR,
  TEXT_COLOR
}